In [1]:
import pandas as pd
import os
import geopandas as gpd
import glob

# os.chdir("/home/ubuntu/real_estate_dashboard")

# 윈도우즈 경로
windows_path = r'C:\Users\ghdau\Desktop\real_estate_dashboard'

# 리눅스 경로로 변환
linux_path = windows_path.replace('\\', '/')

# 작업 디렉토리 변경
os.chdir(linux_path)

print(os.getcwd())

C:\Users\ghdau\Desktop\real_estate_dashboard

In [2]:
file_dir = linux_path + '/0_data/geoservice/sig.shp'
# file_dir = '/0_data/geoservice/sig.shp'

geo_data = gpd.read_file(file_dir, dtype = {'SIG_CD' : 'object'},encoding = 'euc-kr')
geo_data

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry
0,11110,Jongno-gu,종로구,"POLYGON ((956615.453 1953567.199, 956621.579 1..."
1,11140,Jung-gu,중구,"POLYGON ((957890.386 1952616.746, 957909.908 1..."
2,11170,Yongsan-gu,용산구,"POLYGON ((953115.761 1950834.084, 953114.206 1..."
3,11200,Seongdong-gu,성동구,"POLYGON ((959681.109 1952649.605, 959842.412 1..."
4,11215,Gwangjin-gu,광진구,"POLYGON ((964825.058 1952633.250, 964875.565 1..."
...,...,...,...,...
245,48870,Hamyang-gun,함양군,"POLYGON ((1017715.723 1751280.191, 1017761.619..."
246,48880,Geochang-gun,거창군,"POLYGON ((1034571.593 1767759.812, 1034559.208..."
247,48890,Hapcheon-gun,합천군,"POLYGON ((1054066.576 1759517.415, 1054101.450..."
248,50110,Jeju-si,제주시,"MULTIPOLYGON (((874410.953 1480515.382, 874408..."
249,50130,Seogwipo-si,서귀포시,"MULTIPOLYGON (((885004.560 1458756.461, 884996..."

In [3]:
geo_data.crs = 'EPSG:5179'
geo_data = geo_data.to_crs({'init':'EPSG:4326'})

geo_data

C:\Users\ghdau\anaconda3\envs\pybook\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry
0,11110,Jongno-gu,종로구,"POLYGON ((127.00864 37.58047, 127.00871 37.580..."
1,11140,Jung-gu,중구,"POLYGON ((127.02314 37.57196, 127.02336 37.571..."
2,11170,Yongsan-gu,용산구,"POLYGON ((126.96918 37.55566, 126.96917 37.554..."
3,11200,Seongdong-gu,성동구,"POLYGON ((127.04341 37.57234, 127.04524 37.571..."
4,11215,Gwangjin-gu,광진구,"POLYGON ((127.10166 37.57240, 127.10224 37.572..."
...,...,...,...,...
245,48870,Hamyang-gun,함양군,"POLYGON ((127.69596 35.75773, 127.69647 35.757..."
246,48880,Geochang-gun,거창군,"POLYGON ((127.88313 35.90586, 127.88299 35.905..."
247,48890,Hapcheon-gun,합천군,"POLYGON ((128.09861 35.83067, 128.09899 35.830..."
248,50110,Jeju-si,제주시,"MULTIPOLYGON (((126.15092 33.30877, 126.15090 ..."
249,50130,Seogwipo-si,서귀포시,"MULTIPOLYGON (((126.26745 33.11373, 126.26737 ..."

In [6]:
# 법정동코드 불러오기
logal_info_b = pd.read_csv('0_data/legal_info_b.csv', dtype= {'법정동코드':'str'})

# 시도코드 생성
logal_info_b['시도코드'] = logal_info_b['법정동코드'].str[:2]

# 시도코드 , 시도명 코드 생성
logal_info_b_2 = logal_info_b[['시도코드','시도명']].drop_duplicates().reset_index(drop=True)
logal_info_b_2

   시도코드      시도명
0    11    서울특별시
1    26    부산광역시
2    27    대구광역시
3    28    인천광역시
4    29    광주광역시
5    30    대전광역시
6    31    울산광역시
7    36  세종특별자치시
8    41      경기도
9    42      강원도
10   43     충청북도
11   44     충청남도
12   45     전라북도
13   46     전라남도
14   47     경상북도
15   48     경상남도
16   50  제주특별자치도

In [8]:
geo_data['시도코드'] = geo_data['SIG_CD'].str[:2]

geo_data2 = pd.merge(geo_data,logal_info_b_2,
                   on = '시도코드',
                   how = 'left')
geo_data2

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry,시도코드,시도명
0,11110,Jongno-gu,종로구,"POLYGON ((127.00864 37.58047, 127.00871 37.580...",11,서울특별시
1,11140,Jung-gu,중구,"POLYGON ((127.02314 37.57196, 127.02336 37.571...",11,서울특별시
2,11170,Yongsan-gu,용산구,"POLYGON ((126.96918 37.55566, 126.96917 37.554...",11,서울특별시
3,11200,Seongdong-gu,성동구,"POLYGON ((127.04341 37.57234, 127.04524 37.571...",11,서울특별시
4,11215,Gwangjin-gu,광진구,"POLYGON ((127.10166 37.57240, 127.10224 37.572...",11,서울특별시
...,...,...,...,...,...,...
245,48870,Hamyang-gun,함양군,"POLYGON ((127.69596 35.75773, 127.69647 35.757...",48,경상남도
246,48880,Geochang-gun,거창군,"POLYGON ((127.88313 35.90586, 127.88299 35.905...",48,경상남도
247,48890,Hapcheon-gun,합천군,"POLYGON ((128.09861 35.83067, 128.09899 35.830...",48,경상남도
248,50110,Jeju-si,제주시,"MULTIPOLYGON (((126.15092 33.30877, 126.15090 ...",50,제주특별자치도
249,50130,Seogwipo-si,서귀포시,"MULTIPOLYGON (((126.26745 33.11373, 126.26737 ...",50,제주특별자치도

In [9]:
for i in range(len(logal_info_b_2)):
    sd_code = logal_info_b_2['시도코드'][i]
    sd_nm = logal_info_b_2['시도명'][i]
    
    geo_data_cd = geo_data2[geo_data2['시도코드'] == sd_code]
    
    geo_data_cd.to_file(linux_path + f'/0_data/geoservice/geo_sig_{sd_nm}_json.geojsion',
                       encoding='utf-8',driver='GeoJSON')